# Generated by Django 5.0.9 on 2024-10-13 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_lifecycle', '0013_fix_hardware_lifecycle_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='hardwarelifecycle',
            name='renewal_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
